#!/bin/bash
# qa-pathfinder — Map user paths from source code analysis + HTTP tracing
# Usage: qa-run.sh <project-path> <backend-port> [frontend-port]
# Examples:
#   qa-run.sh ~/Projects/RTO_Toolkit 5677 5173
#   qa-run.sh ~/Projects/RTO_Toolkit 8000

set -e

PROJECT_PATH="${1:-.}"
BACKEND_PORT="${2:-8000}"
FRONTEND_PORT="${3:-5173}"

PROJECT_ROOT="$(cd "$PROJECT_PATH" && git rev-parse --show-toplevel 2>/dev/null || echo "$PROJECT_PATH")"
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"

echo "=== qa-pathfinder ==="
echo "  Project: $PROJECT_ROOT"
echo "  Backend: localhost:$BACKEND_PORT"
echo "  Frontend: localhost:$FRONTEND_PORT"

# Phase 1: Source discovery
echo ""
echo "[Phase 1] Source discovery..."

# Detect framework
if [ -f "$PROJECT_PATH/src/App.jsx" ] || [ -f "$PROJECT_PATH/src/App.tsx" ]; then
  FRONTEND="react"
elif [ -f "$PROJECT_PATH/pages" ] || [ -f "$PROJECT_PATH/app" ]; then
  FRONTEND="nextjs"
else
  FRONTEND="unknown"
fi

if [ -f "$PROJECT_PATH/backend/main.py" ] || [ -f "$PROJECT_PATH/routes" ]; then
  BACKEND="fastapi"
else
  BACKEND="unknown"
fi

echo "  Frontend: $FRONTEND"
echo "  Backend: $BACKEND"

# Map frontend routes
echo ""
echo "  Frontend routes:"
if [ "$FRONTEND" = "react" ]; then
  grep -rn "Route\|Routes\|useRoute\|Link\|href\|navigate\|push\|path" "$PROJECT_PATH/src/" --include="*.jsx" --include="*.tsx" 2>/dev/null | grep -v "css\|className\|style\|color\|padding\|margin\|text\|flex\|grid\|width\|height\|border\|background\|position\|display\|aria" | head -30
elif [ "$FRONTEND" = "nextjs" ]; then
  find "$PROJECT_PATH/pages" "$PROJECT_PATH/app" -name "*.tsx" -o -name "*.ts" -o -name "*.jsx" -o -name "*.js" 2>/dev/null | head -20
fi

# Map API endpoints
echo ""
echo "  API endpoints:"
if [ "$BACKEND" = "fastapi" ]; then
  grep -rn "@router\|@app\|@get\|@post\|@put\|@delete" "$PROJECT_PATH/backend/" --include="*.py" 2>/dev/null | grep -v __pycache__ | head -30
fi

# Phase 2: HTTP tracing
echo ""
echo "[Phase 2] HTTP tracing..."

echo "  Health check:"
curl -s "http://localhost:$BACKEND_PORT/health" 2>/dev/null && echo "" || echo "  Backend not reachable"

echo "  API info:"
curl -s "http://localhost:$BACKEND_PORT/api" 2>/dev/null && echo "" || echo "  No /api endpoint"

# Trace key endpoints
echo "  SDR status:"
curl -s "http://localhost:$BACKEND_PORT/api/sdr/status" 2>/dev/null && echo "" || echo "  /api/sdr/status not reachable"

echo "  GMRS channels:"
curl -s "http://localhost:$BACKEND_PORT/api/gmrs/channels" 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(f'  channels: {len(d.get(\"channels\",[]))}, tones: {len(d.get(\"ctcss_tones\",{}))}')" 2>/dev/null || echo "  /api/gmrs/channels not reachable"

echo "  SDR spectrum:"
curl -s "http://localhost:$BACKEND_PORT/api/sdr/spectrum" 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(f'  bins: {len(d.get(\"data\",[]))}')" 2>/dev/null || echo "  /api/sdr/spectrum not reachable"

# Phase 3: Generate PATHS.md
echo ""
echo "[Phase 3] Generating PATHS.md..."

PATHS_FILE="$PROJECT_ROOT/PATHS.md"

cat > "$PATHS_FILE" << 'HEADER'
# Discovered Paths

Generated by qa-pathfinder — source code analysis + HTTP tracing.

HEADER

echo "  Written: $PATHS_FILE"
echo ""
echo "Done. Review $PATHS_FILE and add user path descriptions."